name: Build and Push Connector Runtime Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version number of release: ^[0-9]+.[0-9]+.[0-9]+(-[a-zA-Z0-9.-]+){0,1}$'
        required: true
      branch:
        description: 'Git branch of Dockerfile to be used in the release'
        default: 'main'
      push-latest:
        description: 'Push docker image with latest tag, i.e. this is the latest stable version released'
        type: boolean
        default: true

jobs:
  build-and-push:
    name: Build and Push Connector Runtime Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false # we rely on step outputs, no need for environment variables
          secrets: |
            secret/data/products/connectors/ci/common DOCKERHUB_USER;
            secret/data/products/connectors/ci/common DOCKERHUB_PASSWORD;

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.secrets.outputs.DOCKERHUB_USER }}
          password: ${{ steps.secrets.outputs.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image tag ${{ github.event.inputs.version }} - Runtime
        uses: docker/build-push-action@v4
        with:
          context: runtime
          push: true
          tags: camunda/connectors:${{ github.event.inputs.version }}

      - name: Build and Push Docker Image with tag latest - Runtime
        if: github.event.inputs.push-latest == 'true'
        uses: docker/build-push-action@v4
        with:
          context: runtime
          push: true
          tags: camunda/connectors:latest

      - name: Build and Push Docker Image tag ${{ github.event.inputs.version }} - Bundle
        uses: docker/build-push-action@v4
        with:
          context: bundle
          push: true
          tags: camunda/connectors-bundle-bash:${{ github.event.inputs.version }}

      - name: Build and Push Docker Image with tag latest - Bundle
        if: github.event.inputs.push-latest == 'true'
        uses: docker/build-push-action@v4
        with:
          context: bundle
          push: true
          tags: camunda/connectors-bundle-bash:latest

      - name: Tag version
        run: |
          tag=${{ github.event.inputs.version }}
          message='ci: release version ${{ github.event.inputs.version }}'
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"

      - name: Create GitHub release
        run: gh release create --generate-notes ${RELEASE_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ github.event.inputs.version }}
